version: '3.9'
services:
  db:
    container_name: db
    restart: always
    image: postgres:16-alpine
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=system
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # host_port:container_port
    networks:
      - database_private
      - database
    healthcheck:
      test: pg_isready -U buff -d buff
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  database_private:
    external: true
  database:
    external: true
    name: database