CREATE TABLE IF NOT EXISTS book (
	id   BIGSERIAL    NOT NULL PRIMARY KEY,
	title VARCHAR(128) NOT NULL,
	author VARCHAR(128) NOT NULL,
	isbn VARCHAR(16) NOT NULL,
	price NUMERIC NOT NULL,
	published_date TIMESTAMP NOT NULL
);

DELETE FROM book;